### ISSUE TITLE
[QUESTION] How do I test a function exit status?

### ISSUE THREAD

**Issue by dotnetCarpenter** [coryb/osht#10]
Hi @coryb.

Thank you for creating this project. I found it via [an answer on StackOverflow](https://stackoverflow.com/a/56567827/205696),

I'm pretty new to Bash so this might be a silly question but I can not find anywhere in the example file where a function is tested, so I thought to ask after trying for half an hour.

I got this simple function that I want to test.

```bash
assertChecksumFile () {
	local checksum_path
	checksum_path=$1

	if [[ ! -a $checksum_path ]]; then
		echoError "$checksum_path is missing - aborting..."
		exit 2
	fi
}
```

In my test I have:

```bash
NRUNS assertChecksumFile "wrong/path"
RUNS assertChecksumFile "$TEST_DIR/fixtures/stripe-linux-checksums.txt"
```

If I remove `RUNS/NRUNS`, the function behaves as expected.

As an alternative to `RUNS`, I tried getting the exit code in another way:

```bash
assertChecksumFile "$TEST_DIR/fixtures/stripe-linux-checksums.txt"
IS "$?" -eq 0
```
But I suspect it is getting the exit code of osht and not my function.
Especially because:

```bash
assertChecksumFile () {
exit 0
}
NRUNS assertChecksumFile "wrong/path"
RUNS assertChecksumFile "$TEST_DIR/fixtures/stripe-linux-checksums.txt"
```
gives me the same result!

```
1..2
ok 1 - NRUNS assertChecksumFile "wrong/path"
# ERROR: ./tests/install-stripe-cli.spec at line 18
not ok 2 - RUNS assertChecksumFile "$TEST_DIR/fixtures/stripe-linux-checksums.txt"
Looks like you failed 1 test of 2.
```

So the short question is, **how do I test a function?**

**Comment by abourree** [comment]
Hi,

A function should not exit but return a status code.

Regards,

Arnaud

Le mar. 29 mars 2022 à 01:57, dotnetCarpenter ***@***.***> a
écrit :

**Comment by dotnetCarpenter** [comment]
So I have to duplicate `exit 2` everywhere I want to assert that the file is missing. That does **not** sound very reasonable. What is the rationale behind _"A function should not exit but return a status code."_ @abourree?

Anyway, **how do I test a function's return code** is the main question here.

I already tried:

```bash
assertChecksumFile () {
	local checksum_path
	checksum_path=$1

	if [[ ! -a $checksum_path ]]; then
		echoError "$checksum_path is missing - aborting..."
		return 2
	fi
	return 0
}
NRUNS assertChecksumFile "wrong/path"
RUNS assertChecksumFile "$TEST_DIR/fixtures/stripe-linux-checksums.txt"
````
Output:
```
1..2
ok 1 - NRUNS assertChecksumFile "wrong/path"
# ERROR: ./tests/install-stripe-cli.spec at line 19
not ok 2 - RUNS assertChecksumFile "$TEST_DIR/fixtures/stripe-linux-checksums.txt"
Looks like you failed 1 test of 2.
```

**Comment by dotnetCarpenter** [comment]
@abourree I can give you a little more detail to why `assertChecksumFile` looks so generic when it really wasn't.

Originally `assertChecksumFile` looked like this:
```bash
readonly STRIPE_LINUX_CHECKSUMS_FILE='stripe-linux-checksums.txt'

...

assertChecksumFile () {
	if [[ ! -a $STRIPE_LINUX_CHECKSUMS_FILE ]]; then
		echoError "$STRIPE_LINUX_CHECKSUMS_FILE is missing - aborting..."
		exit 2
	fi
}
```

But since `$STRIPE_LINUX_CHECKSUMS_FILE` is `readonly`, I could not change the path that `assertChecksumFile` checks, so I could not test both code paths. E.g. The success and failure path. That's why I changed the function to accept a parameter instead.

Still, while I appreciate input to how I can write better Bash code as a beginner, the real question is, how do I test that with osht?

**Comment by abourree** [comment]
Hi,

You made the 1st step to be testable: split your original function in two,
the public one with hardcoder filepath and a sub/internal one with path as
parameter.
For 2nd step your internal function should return a status code you can
test without exiting bash process. Your public function will exit with
returned status if not zero.

Regardes,

Arnaud

Le mar. 29 mars 2022 à 12:07, dotnetCarpenter ***@***.***> a
écrit :

**Comment by dotnetCarpenter** [comment]
@abourree can you please explain to me how to test the return status code from a function in osht?

Nothing I tried helps me to test the return value of a function:

```bash
assertChecksumFile () {
  local condition=$1
  if [[ -z "$condition" ]]; then
    return 1
  fi
  return 0
}

NRUNS assertChecksumFile                # ok 1 - NRUNS assertChecksumFile
RUNS assertChecksumFile 'yes'           # not ok 2 - RUNS assertChecksumFile 'yes'
# or
IS assertChecksumFile -eq 1             # osht.sh: line 355: [: assertChecksumFile: integer expression expected
IS assertChecksumFile 'yes' -eq 0       # osht.sh: line 355: [: yes: binary operator expected
```

This is my main issue, regardless of my architecture.

**Comment by dotnetCarpenter** [comment]
Never mind - I finally figured out my issue - **which was "How do I test a function exit status?"**

The following works as expected:

```bash
assertChecksumFile
IS "$?" -eq 1
assertChecksumFile 'yes'
IS "$?" -eq 0
```

Too bad that the test output can not show the actual subject being tested... 😞 

```tap
1..2
ok 1 - IS "$?" -eq 1
ok 2 - IS "$?" -eq 0
```

**Comment by coryb** [comment]
Yeah, so the RUNS will only work with external scripts, functions embedded in the tests are not available.  For RUNS osht will generate a script in tmp based on the arguments to RUNS, then execute that script.  That script will not have any of the functions you write in the test driver script.  All these checks are pretty crude.  

You might be able to rewrite your test functions or create wrapper test functions to get better messsaging.  If you increase the `_OSHT_DEPTH` variable that will be used for the "stack frame" to print as the message.  So maybe something like this will work better for you:

```
assertChecksumFile () {
    local _OSHT_DEPTH=$(($_OSHT_DEPTH+1))
    IS "$1" != "wrong/path"
}
assertChecksumFile "wrong/path"
assertChecksumFile "$TEST_DIR/fixtures/stripe-linux-checksums.txt"
```
then when you run it you see:
```
1..2
# ERROR: /tmp/test.sh at line 14
not ok 1 - assertChecksumFile "wrong/path"
ok 2 - assertChecksumFile "$TEST_DIR/fixtures/stripe-linux-checksums.txt"
Looks like you failed 1 test of 2.
```

**Comment by dotnetCarpenter** [comment]
@coryb Thank you for you answer. I seem to be really bad at communicating, since I keep getting misunderstood. But we're getting there.

I do not want to test anything in the same file as my testing code. The subject under test is external. I did not realize how `RUNS` is implemented in osht. That's why, for learning osht, I put the subject under test in the same file as the unit test. Not because I want to do that after I have figured out how to write osht tests.

My script under test is _install-stripe-cli_ and the tests are in _tests/install-stripe-cli.spec_.

If I have to split `assertChecksumFile` , it kind of negate the point of the function. I'm left testing if Bash can check for for a file, which is useless. I'm thinking that `assertChecksumFile` is not a good function to test.

Here is a little piece of _install-stripe-cli_, that I want to refactor but first I wanted to write some tests to easily gauge if I'm breaking anything.  I guess it only makes sense to test `setStripeCLI `

```bash
assertChecksumFile () {
	if [[ ! -a $STRIPE_LINUX_CHECKSUMS_FILE ]]; then
		echoError "$STRIPE_LINUX_CHECKSUMS_FILE is missing - aborting..."
		exit 2
	fi
}

setStripeCliFromFileExtension () {
	local -n files=$1
	local file_extension=$2
	local found='false'

	for STRIPE_CLI in "${files[@]}"; do
		if [[ $STRIPE_CLI == *.$file_extension ]]; then
			found='true'
			break;
		fi
	done

	if [ $found = 'false' ]; then
		echoError "There is no installation file that ends with .$file_extension - aborting..."
		exit 8
	fi
}

setStripeCLI () {
	# figure out which file we should download
	assertChecksumFile

	local available_files=($(cat $STRIPE_LINUX_CHECKSUMS_FILE | cut --delimiter=" "  --fields=3))

	if [[ -n $INSTALLATION_METHOD ]]; then
		case $INSTALLATION_METHOD in
			rpm) setStripeCliFromFileExtension available_files $RPM;;
			deb) setStripeCliFromFileExtension available_files $DEB;;
			usr) setStripeCliFromFileExtension available_files $TAR;;
			*)
				echoError "Supplied installation method '$INSTALLATION_METHOD' is not supported - aborting..."
				exit 4;;
		esac
	elif [ $SHOW_PROMPT = 'true' ]; then
		echo "Please, choose which file to install:"

		select STRIPE_CLI in "${available_files[@]}"; do
			if [[ "$REPLY" =~ ^[0-9]+$ ]] && [ "$REPLY" -le $((${#available_files[@]})) ]; then
				break;
			else
				echoError "Invalid. Select any number from 1-${#available_files[@]}"
			fi
		done
	else
		if [[ -n $(which rpm) ]]; then
			setStripeCliFromFileExtension available_files $RPM
		elif [[ -n $(which dpkg) ]]; then
			setStripeCliFromFileExtension available_files $DEB
		else
			setStripeCliFromFileExtension available_files $TAR
		fi
	fi
}
```

_tests/install-stripe-cli.spec_:

```bash
#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# set -vx

TEST_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck disable=SC1094
source "$TEST_DIR/osht.sh"
source "$TEST_DIR/../install-stripe-cli"


PLAN 1 # will be incremented with each test case

# tests will go here...
```

Now, is `RUNS` even the right assertion to use for the job?

**Comment by coryb** [comment]
No, `RUNS` is not useful as you have described.  `source` is embedding the scripts in-process, there is no functional difference between using `source` to include a file, or just manually inlining the source directly in the test script.  RUNS requires an external command line tool, not an in-process function call.  If you want to use RUNS you will have to write a command line wrapper script that allows you to execute the functions you want to test.  Or you can use OK/IS with functions defined in your test (or via `source`).  What you had earlier where you test `$?` is the easiest approach.  You will need to ensure the test functions never call `exit` though as you noticed before.   If you want coherent messaging on the `ok 1 ... ` output you will need to wrap the interesting test functions as I mentioned with the _OSHT_DEPTH variable.

**Comment by dotnetCarpenter** [comment]
Thank you @coryb. This is very valuable information! I'm new to Bash, so some of the basic details are unknown to me. Sorry about that.

I think I got enough information to write unit test that will allow me to refactor the code with confidence. Thank you, also to @abourree for enlighten me :)
